URL = "https://useinsider.com/"
COMPANY_PAGE = "//a[normalize-space()='Company']"
CAREER_PAGE = "//a[normalize-space()='Careers']"
CHECK_CONTROL_HOMEPAGE= "//*[span='Let’s Lighten Your Holiday Load ']"
SEE_ALL_TEAMS = "//a[contains(@class, 'loadmore') and text()='See all teams']"
VISIT_QA_JOBS = "//h3[contains(@class, 'text-center') and contains(text(), 'Quality Assurance')]"
SEE_ALL_QA_JOBS = "//*[(text()='See all QA jobs')]"
FILTER_BY_LOCATION = "//*[@id='select2-filter-by-location-container']"
LOCATION_ISTANBUL_TURKEY = "//li[contains(@id, 'select2-filter-by-location-result') and contains(text(), 'Istanbul, Turkiye')]"
FILTER_BY_DEPARTMENT = "//*[@id='select2-filter-by-department-container']"
DEPARTMENT_OF_QA = "//*[@id='select2-filter-by-department-result-qbc6-Quality Assurance']"
CLICK_VIEW_BUTTON = "//a[text()='View Role']"
APPLY_JOB_BUTTON = "//a[text()='Apply for this job']"
COOKIES_ACCEPT_BUTTON = "//a[contains(@class, 'wt-cli-accept-all-btn') and text()='Accept All']"
POPUP_CLOSE_BUTTON = "//*[@class='ins-close-button']"